- name: Suche Partnergateway
  when: "hostvars[supernode].domaenenliste[dom] is defined and supernode != inventory_hostname"
  set_fact:
    domaenenliste: "{{domaenenliste | combine( {dom: {'partner' : gateway}}, recursive=True)}}"
